### ISSUE TITLE
Multivariate Gaussians

### ISSUE THREAD

**Issue by pranavsubramani** [SPFlow/SPFlow#46]
### Description
Implement Multivariate leaves for SPNs

#### Expected behavior:
Multivariate gaussians work as expected and can be used in SPNs as leaves.

**Comment by alejandromolinaml** [comment]
I started writing a multivariate gaussian Leaf.
it turns out marginalization there is going to be a bit more painful :D
but I believe inference at the node works, and MLE should work as well.

I got stuck on the learning part, because when you have mixtures of parametric types (Gaussians, Categorical), then the current code will try to learn everything using a mv gaussian.

this needs a bit more tweaking, but if you are implementing a different learning algorithm, then maybe it works for you already?

other operations are not implemented yet (MPE, sampling, etc)

**Comment by pranavsubramani** [comment]
Hey Alejandro, no worries, I was wondering if I'd be able to help you write this maybe? I think in the prometheus paper, they require multivariate gaussians (so we're ideally trying to get it working for this).

This was previously implemented in the pytorch component, I can re-implement it and maybe we can reconstruct it in the tensorflow version as well? :D

**Comment by pranavsubramani** [comment]
@alejandromolinaml could you point me to the code for it?

**Comment by alejandromolinaml** [comment]
sure, 
It's in the parametric module for now. 

I believe we have to add something to mark leaves as multivariate - univariate, 
only then I can modify the current learning algorithms :)

**Comment by pranavsubramani** [comment]
Hey @alejandromolinaml  I don't see it in the parametric module, could you point me to it?

**Comment by alejandromolinaml** [comment]
sorry, try again

**Comment by steven-lang** [comment]
Jfyi, the recent PR (#57) with the layerwise pytorch stuff includes a MultivariateNormal layer: https://github.com/steven-lang/SPFlow/blob/d5c32c750b865610db1af6eb6098707a3ca39157/src/spn/algorithms/layerwise/distributions.py#L99 (no mpe or sampling implemented though).
